apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    service: gateway
spec:
  ports:
    - port: 8080 # change this to the desired port if needed
      protocol: TCP
      targetPort: 8080 # change this to the desired port if needed
      nodePort: 31808 # change this to the desired port if needed
  type: NodePort
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway # change this to the desired name if needed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway # change this to the desired label if needed
  template:
    metadata:
      labels:
        app: gateway # change this to the desired label if needed
        routectl-name: gateway
        routectl-ns: placeholder
    spec:
      containers:
        - image: $IMAGE_NAME # change this to the desired image if needed
          imagePullPolicy: Always
          name: gateway # change this to the desired name if needed
          ports:
            - containerPort: 8080 # change this to the desired port if needed
              name: http # change this to the desired name if needed
              apiVersion: v1
          resources: {}
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: gateway-config
