@base_url = http://localhost:8080

### Test /material/put
POST http://localhost:8080/material/put
Content-Type: application/json

{
  "materialId": 1,
  "number": 7,
  "userId": 1
}

### Test /material/take
POST http://localhost:8080/material/take
Content-Type: application/json

{
  "materialId": 1,
  "number": 2,
  "userId": 1
}

### Test /material/deleteById
POST http://localhost:8080/material/deleteById
Content-Type: application/json

{
  "materialId": 1,
  "userId": 1
}

### Test /materialRecord/getByRecordId
POST http://localhost:8080/materialRecord/getByRecordId
Content-Type: application/json

{
  "recordId": 1
}

### Test /materialRecord/getAllByOptUserId
POST http://localhost:8080/materialRecord/getAllByOptUserId
Content-Type: application/json

{
  "userId": 1
}

### Test /materialRecord/getAllByOptUserIdAndDate
POST http://localhost:8080/materialRecord/getAllByOptUserIdAndDate
Content-Type: application/json

{
  "userId": 1,
  "start": "Mon, 1 Jan 2024 18:27:50 CST",
  "end": "Sat, 4 May 2024 18:27:50 GMT"
}

### Test /materialRecord/deleteById
POST http://localhost:8080/materialRecord/deleteById
Content-Type: application/json

{
  "recordId": 1
}

### Test /materialRecord/deleteByOptUserId
POST http://localhost:8080/materialRecord/deleteByOptUserId
Content-Type: application/json

{
  "userId": 1
}