server:
  port: 8080
spring:
  application:
    name: BasicOCR
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://${REGISTRY_IP}:${REGISTRY_PORT}/eureka
