### 获取所有客户端信息
POST http://localhost:8080/operation/getAllClientInfo
Content-Type: application/json

### 根据ID获取指定的的客户端信息
POST http://localhost:8080/operation/getClientInfoById
Content-Type: application/json

{
    "id": "this_is_id"
}

### radioToClient
POST http://localhost:8080/forward/radioToClient
Content-Type: application/json

{
  "message": {
    "messageInfo": "string",
    "messageState": 0,
    "messageTime": "string"
  },
  "messageType": "CLIENT_TO_SERVER",
  "sourceId": "string",
  "targetId": "string"
}

### radioToServer
POST http://localhost:8080/forward/radioToServer
Content-Type: application/json

{
  "message": {
    "messageInfo": "string",
    "messageState": 0,
    "messageTime": "string"
  },
  "messageType": "CLIENT_TO_SERVER",
  "sourceId": "string",
  "targetId": "string"
}

### forwardOne
POST http://localhost:8080/forward/forwardOne
Content-Type: application/json

{
  "message": {
    "messageInfo": "string",
    "messageState": 0,
    "messageTime": "string"
  },
  "messageType": "CLIENT_TO_SERVER",
  "sourceId": "string",
  "targetId": "string"
}

### 接收信息
POST http://localhost:8080/server/recieveMessage
Content-Type: application/json

{
  "message": {
    "messageInfo": "string",
    "messageState": 0,
    "messageTime": "string"
  },
  "messageType": "CLIENT_TO_SERVER",
  "sourceId": "string",
  "targetId": "string"
}

### radioToServer
POST http://localhost:8080/server/radioToServer
Content-Type: application/json

{
  "messageInfo": "string",
  "messageState": 0,
  "messageTime": "string"
}

### radioToClient
POST http://localhost:8080/server/radioToClient
Content-Type: application/json

{
  "messageInfo": "string",
  "messageState": 0,
  "messageTime": "string"
}

### 注册客户端
POST http://localhost:8080/server/register
Content-Type: application/json

{
    "clientInfo": {
        "clientId": "your_clientId_here",
        "ip": "127.0.0.1",
        "location": {
            "lat": 1,
            "lng": 2,
            "location": "your_location_here"
        }
    }
}

### 发送信息
POST http://localhost:8080/server/sendMessage
Content-Type: application/json

{
    "notice": {
        "message": {
            "messageInfo": "your_messageInfo_here",
            "messageState": 0,
            "messageTime": "your_messageTime_here"
        },
        "messageType": "your_messageType_here",
        "sourceId": "your_sourceId_here",
        "targetId": "your_targetId_here"
    }
}