
### radioToClient
POST http://localhost:8080/client/radioToCLient
Content-Type: application/json

{
  "messageInfo": "string",
  "messageState": 0,
  "messageTime": "string"
}

### radioToServer
POST http://localhost:8080/client/radioToServer
Content-Type: application/json

{
  "messageInfo": "string",
  "messageState": 0,
  "messageTime": "string"
}


### 接收信息
POST http://localhost:8080/client/recieveMessage
Content-Type: application/json

{
  "message": {
    "messageInfo": "string",
    "messageState": 0,
    "messageTime": "string"
  },
  "messageType": "CLIENT_TO_SERVER",
  "sourceId": "string",
  "targetId": "string"
}


### 注册客户端
POST http://localhost:8080/client/seeClients

### 发送信息
POST http://localhost:8080/client/sendMessage
Content-Type: application/json

{
  "message": {
    "messageInfo": "string",
    "messageState": 0,
    "messageTime": "string"
  },
  "messageType": "CLIENT_TO_SERVER",
  "sourceId": "string",
  "targetId": "string"
}