server:
  port: 8080

spring:
  application:
    name: PatientInfo
  thymeleaf:
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/ #前缀
    suffix: .html
    mode: HTML
    cache: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
